# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/alex/zynq/red-pitaya/ip_repo/edit_rri_control_v1_0/edit_rri_control_v1_0.srcs/sources_1/ip/dac_block_ram_gen/dac_block_ram_gen.xci
# IP: The module: 'dac_block_ram_gen' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/alex/zynq/red-pitaya/ip_repo/edit_rri_control_v1_0/edit_rri_control_v1_0.srcs/sources_1/ip/dac_block_ram_gen/dac_block_ram_gen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dac_block_ram_gen'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/alex/zynq/red-pitaya/ip_repo/edit_rri_control_v1_0/edit_rri_control_v1_0.srcs/sources_1/ip/dac_block_ram_gen/dac_block_ram_gen.xci
# IP: The module: 'dac_block_ram_gen' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/alex/zynq/red-pitaya/ip_repo/edit_rri_control_v1_0/edit_rri_control_v1_0.srcs/sources_1/ip/dac_block_ram_gen/dac_block_ram_gen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dac_block_ram_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
